name: CI/CD Pipeline

# ЗАЧЕМ: Говорим Actions, когда запускаться
on:
  push:                    # При пуше кода
    branches: [ master ]     # только в ветку main
  pull_request:            # При запросе на слияние
    branches: [ master ]

# ЗАЧЕМ: Что конкретно делать
jobs:
  # JOB 1: ПРОВЕРКА (CI)
  test:
    runs-on: ubuntu-latest   # Запускаем на виртуальной Ubuntu
    steps:
      - name: Скачать код
        uses: actions/checkout@v4   # Забираем код из репозитория

      - name: Установить Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Запустить тесты
        run: python test_calculator.py   # Выполняем тесты
      - name : Ещё один крутой тест
        run: python test_test.py

      - name: Показать, что код работает
        run: python calculator.py
      - name: Показать бесполезный код
        run: newfile.py

  # JOB 2: РАЗВЕРТЫВАНИЕ (CD)
  deploy:
    runs-on: ubuntu-latest
    needs: test            # ЗАЧЕМ: Запускать ТОЛЬКО если test успешен
    steps:
      - name: Симуляция деплоя
        run: |
          echo "🚀 Деплоим приложение..."
          echo "✅ Приложение развернуто на https://my-app.com"